app = "once-verifier"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = ""

[env]
  BACKEND_BASE_URL = "https://api.getonce.com"
  SIGNING_KEY_ID = "default"
  ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
